### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by FieryVector** [Kxnrl/NeptuniaCSGO#1]
How do I load this addon?
It won't load at the gamestart and the 2 commands sm_nep and sm_neptunia are not working.
Your installation instructions are not to hard, but do I need any other addons?
Not for the knife, just for the models.

Reaper951

**Comment by Kxnrl** [comment]
do u run sourcemod and metamod?
https://sm.sourcemod.net
https://www.sourcemm.net

**Comment by FieryVector** [comment]
Thanks. It's working now.
Can I replace the bots I see too and not only me?

And I have an other question about VAC.
Do I have to remove the mods when I play without "-insecure" or are this 3 mods "safe"?

**Comment by Kxnrl** [comment]
Mod is safe，but i am not sure use third-party addon( soucemod and metamod) will get VAC ban… and now u can make bot mod by kv… i will add bot controller in nextversion
